stages:
  - test

cover_test:
  stage: test
  image: golang:latest
  cache:
    paths:
      - /apt-cache
      - $GOPATH/src/github.com
      - $GOPATH/src/golang.org
      - $GOPATH/src/google.golang.org
      - $GOPATH/src/gopkg.in
  before_script:
    - go install github.com/axw/gocov/gocov@latest
  script:
    - gocov test `go list ./...` | gocov report
  coverage: '/Total Coverage: \d+\.\d+/'